export const ORDER_REQUEST='ORDER_REQUEST';
export const ORDER_FAILURE='ORDER-FAILURE';
export const GET_ORDER_SUCCESS='GET_ORDER_SUCCESS';
export const GET_ALL_ORDER_SUCCESS='GET_ALL_ORDER_SUCCESS';
