export const PRODUCT_REQUEST='PRODUCT_REQUEST';
export const PRODUCT_FAILURE='PRODUCT-FAILURE';
export const GET_CART_SUCCESS='GET_CART_SUCCESS';
export const POST_PRODUCT_SUCCESS='POST_PRODUCT_SUCCESS';
export const REMOVE_CART_SUCCESS='REMOVE_PRODUCT_SUCCESS';
export const PATCH_CART_SUCCESS='PATCH_CART_SUCCESS';
