export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const USER_REQUEST='USER_REQUEST';
export const USER_FAILURE='USER-FAILURE';
export const GET_USER_SUCCESS='GET_USER_SUCCESS';
export const GET_ALL_USER_SUCCESS='GET_ALL_USER_SUCCESS';
export const REMOVE_USER_SUCCESS='REMOVE_USER_SUCCESS';
export const PATCH_USER_SUCCESS='PATCH_USER_SUCCESS';

export const LOGOUT = "LOGOUT";